# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48775fa18c3b83a337121e9d68dbcf8718b6a766212dfd708e2924f581f162b488995691543c623a76546bce7dd95169c5255deae3774e43cc84c57b68e6db9

test:
  secret_key_base: 91064ac8c1af25387117ecf7380fd1b895bccb2c99a320351f6e1ec0ff397f71ea63b06b5c6e276a076e54fda8a87c04127829a1a97dd57d26b10b6cc0651289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
